export enum EnvProps {
  DATABASE_URL = 'DATABASE_URL',
  JWT_SECRET_ACCESS_TOKEN = 'JWT_SECRET_ACCESS_TOKEN',
  // GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  // GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
  // GOOGLE_CALLBACK_URL = 'GOOGLE_CALLBACK_URL',
  // SESSION_SECRET = 'SESSION_SECRET',
}
